version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: twitter-api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - postgres:/data/postgres
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: